---
deployment:
  tasks:
    # 1. Backend: Install production dependencies
    - cd server && npm install --production
    
    # 2. Frontend: Install dependencies and build React app
    - cd client && npm install --omit=dev
    - cd client && npm run build
    
    # 3. Frontend: Copy new React build to public_html document root
    - /bin/cp -Rf client/build/. ~/public_html/
    
    # 4. Backend: Restart Node.js application via Passenger
    - touch ~/public_html/tmp/restart.txt
